# Generated by Django 5.2.9 on 2025-12-09 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='accounts_fo_followe_6d6ab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='accounts_fo_followe_4ce64c_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', '-created_at'], name='accounts_fo_followe_592424_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed'], name='accounts_fo_followe_b12cb5_idx'),
        ),
    ]
